### ISSUE TITLE
Module `autoeis.core` has no attribute `apply_heuristic_rules`

### ISSUE THREAD

**Issue by RonM700** [AUTODIAL/AutoEIS#75]
{
	"name": "AttributeError",
	"message": "module 'autoeis.core' has no attribute 'apply_heuristic_rules'",
	"stack": "---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[6], line 1
----> 1 circuits = ae.core.apply_heuristic_rules(circuits_unfiltered)
      2 # Let's save the filtered circuits to a CSV file as well
      3 circuits.to_csv(\"circuits_filtered.csv\", index=False)

AttributeError: module 'autoeis.core' has no attribute 'apply_heuristic_rules'"
}

**Comment by ma-sadeghi** [comment]
Please share a minimal working example that reproduces the bug.

**Comment by RonM700** [comment]
It happens directly when launching the example Jupyter NB of your Repo. When switching to False, a normal run is possible, however I guess you were intending to enable this batch mode exactly int he parallel mode

**Comment by RonM700** [comment]
Hi Amin,

I guess, I spotted a major bug in V0.0.21, regarding CSV, please compare for R4:

￼

54 Ohm in CSV in not plausible, as the table shows a range between 6-13 Ohms, which corresponds to statistical distribution of Bayes.

Best, Ronny

**Comment by ma-sadeghi** [comment]
Hi @RonM700,
Please update to the latest version (v0.0.22 as of now). We've renamed `apply_heuristic_rules` to `filter_implausible_circuits` for clarity.

Also, there's a new version incoming (in a few hours maybe or Monday the latest). Keep an eye. I've also added an automated test to test the example notebook as part of the release workflow.

Regarding the CSV bug: Could you please be more specific, I'm not sure what exactly you're referring to. Also, please open a new issue to follow up there.

**Comment by RonM700** [comment]
Hi Amin,

True, the renaming is done, but still no parallel ECM generation happens, see this screenshot from v.0.0.23
￼

Thank you for checking n repair.
Best, Ronny

**Comment by ma-sadeghi** [comment]
Hey @RonM700, but there's no screenshot, it seems that is hasn't been properly uploaded. Can you upload again? Also, it's easier to debug if you copy and paste the error rather than the screenshot (although that helps too sometimes)

**Comment by RonM700** [comment]
ERROR  Error generating circuits: circuit_evolution_batch             
href="file:///Users/ronnymonnig/ronenv/lib/python3.9/site-packages/autoeis/core.py:425“ 

Seems to be a tqdm error somehow….

**Comment by ma-sadeghi** [comment]
@RonM700 Can you upgrade to the latest version? We just released v0.0.24

**Comment by RonM700** [comment]
Hi Amin,

The error message changed to:

<pre style="white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace"><span style="color: #7fbfbf; text-decoration-color: #7fbfbf">[14:41:43] </span><span style="color: #800000; text-decoration-color: #800000; font-weight: bold">ERROR   </span> Error generating circuits: Julia: UndefVarError: `circuit_evolution_batch` not      <a href="file:///Users/ronnymonnig/ronenv/lib/python3.9/site-packages/autoeis/core.py" target="_blank"><span style="color: #7f7f7f; text-decoration-color: #7f7f7f">core.py</span></a><span style="color: #7f7f7f; text-decoration-color: #7f7f7f">:</span><a href="file:///Users/ronnymonnig/ronenv/lib/python3.9/site-packages/autoeis/core.py#404" target="_blank"><span style="color: #7f7f7f; text-decoration-color: #7f7f7f">404</span></a>
<span style="color: #7fbfbf; text-decoration-color: #7fbfbf">           </span>         defined                                                                             <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">           </span>
</pre>


[14:41:43] ERROR    Error generating circuits: Julia: UndefVarError: `circuit_evolution_batch` not      core.py <>:404 <>
                    defined

**Comment by ma-sadeghi** [comment]
A few notes/questions/possible solution:

- You're using an old Python version, we've already deprecated it. We support 3.10+. But this is almost certainly not the cause of your issue.
- How do you run the example notebook? Inside VS Code? A native web-based Jupyter Lab? etc.
- We have automated tests for most of the public-facing API, as well as the example notebook. The most recent [notebook test](https://github.com/AUTODIAL/AutoEIS/actions/runs/7891458926/job/21535837830?pr=90) has passed, so I suspect there might be something wrong with the local setup, like Python distribution, Jupyter, etc.
- Your error traceback shows that your AutoEIS couldn't find `circuit_evolution_batch`. This function has been added to EquivalentCircuits very recently, so I highly suspect this is the culprit.
- So here's what I suggest you do:
  - First, create a fresh virtual environment with Python 3.10. There are many ways, but if you're using `conda`, run `conda create -n myenv python=3.10`, followed by `conda activate myenv` to activate the environment (also make sure to choose the IPython kernel that matches your virtual environment when running the notebook)
  - Second, install a fresh copy of AutoEIS using `pip install -U autoeis`
  - There's no need to manually install the Julia backend anymore, it's done automatically at first import of the package, so be patient.

**Comment by RonM700** [comment]
Hi Amin,

I changed to Python 3.12.0 and also updated the installed Julia packages, but still same error:

<pre style="white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace"><span style="color: #7fbfbf; text-decoration-color: #7fbfbf">[21:16:24] </span><span style="color: #800000; text-decoration-color: #800000; font-weight: bold">ERROR   </span> Error generating circuits: Julia: UndefVarError: `circuit_evolution_batch` not      <a href="file:///Users/ronnymonnig/.pyenv/versions/3.12.0/lib/python3.12/site-packages/autoeis/core.py" target="_blank"><span style="color: #7f7f7f; text-decoration-color: #7f7f7f">core.py</span></a><span style="color: #7f7f7f; text-decoration-color: #7f7f7f">:</span><a href="file:///Users/ronnymonnig/.pyenv/versions/3.12.0/lib/python3.12/site-packages/autoeis/core.py#404" target="_blank"><span style="color: #7f7f7f; text-decoration-color: #7f7f7f">404</span></a>
<span style="color: #7fbfbf; text-decoration-color: #7fbfbf">           </span>         defined                                                                             <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">           </span>
</pre>

 

> Am 13.02.2024 um 21:00 schrieb Amin Sadeghi ***@***.***>:
> 
> our AutoEIS couldn't find circuit_evolution_batch. This function has been added to EquivalentCircuits very rec

**Comment by ma-sadeghi** [comment]
Open up Julia REPL and run the following snippet and paste the output here:

```julia
julia> using Pkg

julia> Pkg.status()
Status `~/mambaforge/envs/autoeis/julia_env/Project.toml`
  [da5bd070] EquivalentCircuits v0.3.1 `https://github.com/ma-sadeghi/EquivalentCircuits.jl#bug/fix-ndarray-serialization`
  [6099a3de] PythonCall v0.9.15
```

If you don't see "exactly" what's shown above, then it's your Julia installation.

**Comment by RonM700** [comment]
Status `~/.julia/environments/v1.9/Project.toml`
  [336ed68f] CSV v0.10.12
  [8bb1440f] DelimitedFiles v1.9.1
  [da5bd070] EquivalentCircuits v0.3.1
  [eadc2687] Pandas v1.6.1
  [f0f68f2c] PlotlyJS v0.18.12
  [438e738f] PyCall v1.96.4
  [d6ea1423] RobustModels v0.5.0
  [69024149] StringEncodings v0.3.7

**Comment by ma-sadeghi** [comment]
That's your global Julia environment. You need to first activate the Julia environment that's associated with AutoEIS, so let's do something else: Run the following snippet in a Python REPL:

```python
>>> from autoeis.core import jl
>>> jl.Pkg.status()
Status `~/mambaforge/envs/autoeis/julia_env/Project.toml`
  [da5bd070] EquivalentCircuits v0.3.1 `https://github.com/ma-sadeghi/EquivalentCircuits.jl#bug/fix-ndarray-serialization`
  [6099a3de] PythonCall v0.9.15
```

**Comment by RonM700** [comment]
Here is my Output:

>>> from autoeis.core import jl
>>> jl.Pkg.status()
Status `~/.julia/environments/pyjuliapkg/Project.toml`
  [6099a3de] PythonCall v0.9.15


> Am 13.02.2024 um 21:36 schrieb Amin Sadeghi ***@***.***>:
> 
> jl.Pkg.status()

**Comment by ma-sadeghi** [comment]
Okay, then your Julia is not properly initialized. Let's force-reinstall it. In a shell, run:

```shell
python -m autoeis install
```

Then, re-run `status` to see the new output:

```python
>>> from autoeis.core import jl
>>> jl.Pkg.status()
```

Also, please verify your AutoEIS version, I need the output of the following snippet:

```python
import autoeis
print(autoeis.__version__)
print(autoeis.__equivalent_circuits_jl_version__)
```

**Comment by RonM700** [comment]
You were right:

Status `~/.julia/environments/pyjuliapkg/Project.toml`
  [da5bd070] EquivalentCircuits v0.3.1 `https://github.com/ma-sadeghi/EquivalentCircuits.jl#bug/fix-ndarray-serialization`
  [6099a3de] PythonCall v0.9.15

**Comment by RonM700** [comment]
Exzellent, now it works in the parallel mode, fist time for me !!

Amazing job, thank you.

Do I need to repeat that REPL procedure each time when opening VS code?

**Comment by ma-sadeghi** [comment]
Great!

If by REPL procedure, you mean activating the environment, then no, it should automatically pick up the right one by itself.

**Comment by RonM700** [comment]
Fantastic, thank a lot, dear friend.

Best, Ronny
