### ISSUE TITLE
CSV problem when saving filtered ECM with v.0.0.21

### ISSUE THREAD

**Issue by RonM700** [AUTODIAL/AutoEIS#87]
![spotted_error_CSV 03 02 2024](https://github.com/AUTODIAL/AutoEIS/assets/147749464/885554c9-e082-4873-ac1f-c9b8cbc8024f)
There is a transfer/saving error in case of parameter R4 in the obtained CSV from v0.0.21. Please check that, thank you. The value inside the csv file does not reflect the script output, see screenshot

**Comment by ma-sadeghi** [comment]
Hi @RonM700, if you're referring to the CSV files shipped with the package, they're just there so you can skip the ECM generation step, which is quite time consuming, to get you started with the example notebook. They're not meant to be used for a real project. I'm closing this issue, but feel free to re-open if you meant something else.
