### ISSUE TITLE
`jax >= 0.4.24` breaks `multiprocessing` using `fork` as start method

### ISSUE THREAD

**Issue by ma-sadeghi** [AUTODIAL/AutoEIS#94]
Not exactly sure which `jax` version triggered the bug, but probably version >= 0.4.24. Anyway, the fix is to use `spawn` as the start method, it seems at least.

**Comment by benjamin5988** [comment]
can you be more specific on where to replace os.fork with os.spawn?

**Comment by ma-sadeghi** [comment]
I'm afraid the fix might not be that simple. I already tried that, but it seems there might be an API change upstream (either in `mpire` or `multiprocess`) that needs to be monkeypatched until it's fixed. Anyway, I'm a bit occupied at the moment, but will look into it asap since it's a critical bug. In the meantime, maybe downgrade your `jax` to 0.4.23 (or maybe older?) to be able to use AutoEIS.

**Comment by benjamin5988** [comment]
Many thanks!!

**Comment by ma-sadeghi** [comment]
@benjamin5988 A new release was just issued, hopefully it's fixed now. Please let us know if it's not.
